<?php
/**
 * Copyright (c) 2020.
 * Designed and developed by Aleksandr Dremov
 * Use according to the license guidelines.
 * Contact me: dremov.me@gmail.com
 */

require_once __DIR__ . '/../vendor/autoload.php';

use DAIM\Core\Connection;
use DAIM\Core\Credentials;
use PHPUnit\Framework\TestCase;

class BasicTableTest extends TestCase
{

    private $host = '127.0.0.1';

    private $username = 'test';

    private $Dbname = 'daim';

    private $password = 'qwerty123';

    private $port = 3306;

    public function setUp()
    {
        $cred = new Credentials();
        $cred->setHost($this->host);
        $cred->setUsername($this->username);
        $cred->setDbname($this->Dbname);
        $cred->setPassword($this->password);
        $cred->setPort($this->port);
        Connection::setCredentials($cred);
        Connection::initConnection();
    }

    public function testGeneralIncludeAutoload(): void
    {
        $app = new DAIM\Core\BasicTable();
        $this->assertIsObject($app);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}