<?php /**
 * Copyright (c) 2020.
 * Designed and developed by Aleksandr Dremov
 * Use according to the license guidelines.
 * Contact me: dremov.me@gmail.com
 */
/** @noinspection PhpUnhandledExceptionInspection */
require_once __DIR__ . '/../vendor/autoload.php';

use DAIM\Core\Connection;
use DAIM\Core\Credentials;
use PHPUnit\Framework\TestCase;

class BasicTableTest extends TestCase
{

    public function __construct($name = null, array $data = [], $dataName = '')
    {
        parent::__construct($name, $data, $dataName);
        $envVars = json_decode(file_get_contents(__DIR__ . '/environment.json'), true);
        foreach ($envVars as $key => $value) {
            $this->$key = $value;
        }
        foreach ($envVars['database'] as $key => $value) {
            $this->$key = $value;
        }
    }

    public function setUp()
    {
        $cred = new Credentials();
        $cred->setHost($this->host);
        $cred->setUsername($this->username);
        $cred->setDBname($this->DBname);
        $cred->setPassword($this->password);
        $cred->setPort($this->port);
        Connection::setCredentials($cred);
        Connection::initConnection();
    }

    public function testGeneralIncludeAutoload(): void
    {
        $app = new DAIM\Core\BasicTable();
        $this->assertIsObject($app);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}